CC = cc

NAME = philo

#CFLAGS = -Wall -Werror -Wextra
CFLAGS = -Wall -Werror -Wextra -fsanitize=thread

SRCS = philo.c ft_atoi.c

OBJS = $(SRCS:.c=.o)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) -lpthread $(OBJS) -o $(NAME)

%.o : %.c
	$(CC) $(CFLAGS) -g -c $< -o $@

all : $(NAME)

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

debug: all
	$(CC) $(OBJS) -o -lpthread $(NAME)
#$(CC) -lpthread $(OBJS) -o $(NAME) -fsanitize=address

lldb: all
	$(CC) $(CFLAGS) $(SRCS) -o -lpthread $(NAME) -g3

re:
	make fclean
	make all

.PHONY: all clean fclean re
